// Code generated by "stringer -type=EntryType -linecomment"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Debit-0]
	_ = x[Credit-1]
}

const _EntryType_name = "DEBITCREDIT"

var _EntryType_index = [...]uint8{0, 5, 11}

func (i EntryType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EntryType_index)-1 {
		return "EntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntryType_name[_EntryType_index[idx]:_EntryType_index[idx+1]]
}
