// Code generated by "stringer -type=TransferState -linecomment"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatePending-0]
	_ = x[StateProcessed-1]
	_ = x[StateFailed-2]
}

const _TransferState_name = "PENDINGPROCESSEDFAILED"

var _TransferState_index = [...]uint8{0, 7, 16, 22}

func (i TransferState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TransferState_index)-1 {
		return "TransferState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferState_name[_TransferState_index[idx]:_TransferState_index[idx+1]]
}
